const mockProjects = [
  {
    id: 1,
    title: "Smart Home Automation Hub",
    description: "Complete IoT system for home automation with temperature sensors and remote control.",
    author: "Alex Chen",  // Alex Chen - Project 1
    category: "Arduino",
    tags: ["Arduino", "IoT", "Sensors"],
    likes: 234,
    comments: 45,
    imageUrl: "https://source.unsplash.com/400x300/?smart-home,iot",
    createdAt: "2025-01-05"
  },
  {
    id: 2,
    title: "WiFi Weather Station",
    description: "ESP32-based weather monitoring system with cloud connectivity and data logging.",
    author: "Sarah Martinez",
    category: "ESP32",
    tags: ["ESP32", "Sensors", "IoT"],
    likes: 180,
    comments: 32,
    imageUrl: "https://source.unsplash.com/400x300/?weather,station",
    createdAt: "2025-01-12"
  },
  {
    id: 3,
    title: "AI-Powered Robot Car",
    description: "Autonomous robot car using Raspberry Pi with computer vision and obstacle avoidance.",
    author: "Michael Park",
    category: "Robotics",
    tags: ["Robotics", "Raspberry Pi"],
    likes: 412,
    comments: 91,
    imageUrl: "https://source.unsplash.com/400x300/?robot,car",
    createdAt: "2025-01-19"
  },
  {
    id: 4,
    title: "USB-C Power Delivery Board",
    description: "Custom PCB for USB-C power delivery with overvoltage and thermal protection.",
    author: "Emma Wilson",
    category: "PCB Design",
    tags: ["PCB Design", "Sensors"],
    likes: 366,
    comments: 45,
    imageUrl: "https://source.unsplash.com/400x300/?pcb,circuit",
    createdAt: "2025-01-26"
  },
  {
    id: 5,
    title: "Digital Oscilloscope DIY",
    description: "Build a compact oscilloscope using STM32 microcontroller and TFT display.",
    author: "David Kumar",
    category: "STM32",
    tags: ["STM32", "Sensors"],
    likes: 298,
    comments: 61,
    imageUrl: "https://source.unsplash.com/400x300/?oscilloscope,stm32",
    createdAt: "2025-02-02"
  },
  {
    id: 6,
    title: "LoRa Sensor Network",
    description: "Long-range wireless environmental monitoring with sensors and LoRa communication.",
    author: "Jessica Lee",
    category: "IoT",
    tags: ["IoT", "Sensors"],
    likes: 367,
    comments: 80,
    imageUrl: "https://source.unsplash.com/400x300/?lora,network",
    createdAt: "2025-02-09"
  },
  {
    id: 7,
    title: "Smart Light Controller",
    description: "Arduino-based RGB lighting controller with sound-reactive effects.",
    author: "Alex Chen",  // Alex Chen - Project 2
    category: "Arduino",
    tags: ["Arduino", "Sensors"],
    likes: 255,
    comments: 40,
    imageUrl: "https://source.unsplash.com/400x300/?arduino,led",
    createdAt: "2025-02-16"
  },
  {
    id: 8,
    title: "Raspberry Pi Media Center",
    description: "Transform your TV into a smart entertainment center using Raspberry Pi.",
    author: "Daniel Cho",
    category: "Raspberry Pi",
    tags: ["Raspberry Pi"],
    likes: 512,
    comments: 74,
    imageUrl: "https://source.unsplash.com/400x300/?raspberry-pi,media",
    createdAt: "2025-02-23"
  },
  {
    id: 9,
    title: "3D Printed Robot Arm",
    description: "Robotic arm with servo control for automation tasks and teaching robotics.",
    author: "Linda Wong",
    category: "Robotics",
    tags: ["Robotics", "Arduino"],
    likes: 342,
    comments: 66,
    imageUrl: "https://source.unsplash.com/400x300/?robot,arm",
    createdAt: "2025-03-02"
  },
  {
    id: 10,
    title: "ESP32 Security Camera",
    description: "Compact camera module using ESP32-CAM with motion detection alerts.",
    author: "Amir Rahman",
    category: "ESP32",
    tags: ["ESP32", "IoT"],
    likes: 412,
    comments: 59,
    imageUrl: "https://source.unsplash.com/400x300/?camera,esp32",
    createdAt: "2025-03-09"
  },
  {
    id: 11,
    title: "Plant Monitoring System",
    description: "IoT-based plant health tracker using moisture and light sensors.",
    author: "Sabrina Ho",
    category: "IoT",
    tags: ["IoT", "Sensors", "Arduino"],
    likes: 289,
    comments: 43,
    imageUrl: "https://source.unsplash.com/400x300/?plant,iot",
    createdAt: "2025-03-16"
  },
  {
    id: 12,
    title: "Environmental Air Monitor",
    description: "Portable PM2.5, temperature and humidity monitoring device.",
    author: "Kevin Liu",
    category: "Sensors",
    tags: ["Sensors", "ESP32"],
    likes: 301,
    comments: 51,
    imageUrl: "https://source.unsplash.com/400x300/?air,quality",
    createdAt: "2025-03-23"
  },
  {
    id: 13,
    title: "Raspberry Pi Retro Console",
    description: "Build a retro gaming console using Raspberry Pi and RetroPie.",
    author: "George Tan",
    category: "Raspberry Pi",
    tags: ["Raspberry Pi"],
    likes: 478,
    comments: 90,
    imageUrl: "https://source.unsplash.com/400x300/?retro,gaming",
    createdAt: "2025-03-30"
  },
  {
    id: 14,
    title: "Smart Mirror Display",
    description: "Two-way mirror with Raspberry Pi displaying weather and calendar.",
    author: "Emily Zhao",
    category: "Raspberry Pi",
    tags: ["Raspberry Pi", "IoT"],
    likes: 612,
    comments: 103,
    imageUrl: "https://source.unsplash.com/400x300/?mirror,smart",
    createdAt: "2025-04-06"
  },
  {
    id: 15,
    title: "PCB Power Regulator",
    description: "Efficient voltage regulator board with custom PCB layout.",
    author: "Hassan Noor",
    category: "PCB Design",
    tags: ["PCB Design"],
    likes: 320,
    comments: 47,
    imageUrl: "https://source.unsplash.com/400x300/?pcb,board",
    createdAt: "2025-04-13"
  },
  {
    id: 16,
    title: "STM32 Flight Controller",
    description: "Lightweight drone flight controller developed using STM32 MCU.",
    author: "Julie Kim",
    category: "STM32",
    tags: ["STM32", "Sensors"],
    likes: 456,
    comments: 88,
    imageUrl: "https://source.unsplash.com/400x300/?drone,controller",
    createdAt: "2025-04-20"
  },
  {
    id: 17,
    title: "Robotic Line Follower",
    description: "Simple robotics project using IR sensors and Arduino.",
    author: "Ben Carter",
    category: "Robotics",
    tags: ["Robotics", "Arduino", "Sensors"],
    likes: 410,
    comments: 79,
    imageUrl: "https://source.unsplash.com/400x300/?robot,line",
    createdAt: "2025-04-27"
  },
  {
    id: 18,
    title: "Smart Thermostat",
    description: "AI-enabled thermostat using ESP32 with temperature prediction.",
    author: "Karen White",
    category: "IoT",
    tags: ["IoT", "ESP32", "Sensors"],
    likes: 389,
    comments: 72,
    imageUrl: "https://source.unsplash.com/400x300/?thermostat,iot",
    createdAt: "2025-05-04"
  },
  {
    id: 19,
    title: "RFID Door Lock System",
    description: "Arduino-controlled security lock using RFID authentication.",
    author: "Alex Chen",  // Alex Chen - Project 3
    category: "Arduino",
    tags: ["Arduino", "Sensors"],
    likes: 312,
    comments: 58,
    imageUrl: "https://source.unsplash.com/400x300/?rfid,lock",
    createdAt: "2025-05-11"
  },
  {
    id: 20,
    title: "ESP32 GPS Tracker",
    description: "Vehicle tracking system with GPS and IoT cloud logging.",
    author: "Rachel Adams",
    category: "ESP32",
    tags: ["ESP32", "IoT"],
    likes: 445,
    comments: 87,
    imageUrl: "https://source.unsplash.com/400x300/?gps,esp32",
    createdAt: "2025-05-18"
  },
  {
    id: 21,
    title: "STM32 Robot Controller",
    description: "Advanced robot motor and sensor controller using STM32.",
    author: "Daniel Foster",
    category: "STM32",
    tags: ["STM32", "Robotics"],
    likes: 534,
    comments: 98,
    imageUrl: "https://source.unsplash.com/400x300/?stm32,robot",
    createdAt: "2025-05-25"
  },
  {
    id: 22,
    title: "PCB Sensor Module",
    description: "Modular PCB with multiple integrated environmental sensors.",
    author: "Alex Chen",  // Alex Chen - Project 4
    category: "PCB Design",
    tags: ["PCB Design", "Sensors"],
    likes: 278,
    comments: 52,
    imageUrl: "https://source.unsplash.com/400x300/?pcb,sensor",
    createdAt: "2025-06-01"
  },
  {
    id: 23,
    title: "Raspberry Pi Home Server",
    description: "Always-on home server with backups, media, and file storage.",
    author: "Kevin Zhang",
    category: "Raspberry Pi",
    tags: ["Raspberry Pi"],
    likes: 823,
    comments: 167,
    imageUrl: "https://source.unsplash.com/400x300/?server,raspberrypi",
    createdAt: "2025-06-08"
  },
  {
    id: 24,
    title: "Arduino Pet Feeder",
    description: "Automated pet feeder with scheduling and weight sensors.",
    author: "Julia Martinez",
    category: "Arduino",
    tags: ["Arduino", "Sensors"],
    likes: 456,
    comments: 84,
    imageUrl: "https://source.unsplash.com/400x300/?pet,arduino",
    createdAt: "2025-06-15"
  }
];